src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChambreRepository::class)
 */
class Chambre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description_short;

    /**
     * @ORM\Column(type="text")
     */
    private $description_long;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @ORM\Column(type="integer")
     */
    private $price_day;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_register;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="id_chambre")
     */
    private $commandes;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

  



    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescriptionShort(): ?string
    {
        return $this->description_short;
    }

    public function setDescriptionShort(string $description_short): self
    {
        $this->description_short = $description_short;

        return $this;
    }

    public function getDescriptionLong(): ?string
    {
        return $this->description_long;
    }

    public function setDescriptionLong(string $description_long): self
    {
        $this->description_long = $description_long;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPriceDay(): ?int
    {
        return $this->price_day;
    }

    public function setPriceDay(int $price_day): self
    {
        $this->price_day = $price_day;

        return $this;
    }

    public function getDateRegister(): ?\DateTimeInterface
    {
        return $this->date_register;
    }

    public function setDateRegister(\DateTimeInterface $date_register): self
    {
        $this->date_register = $date_register;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setChambre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getChambre() === $this) {
                $commande->setChambre(null);
            }
        }

        return $this;
    }


    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

}

src/Controller/ReservationsController.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ReservationsController extends AbstractController
{
    /**
    * @Route("/voir-chambres-reservation", name="show_reservation", methods={"GET"})
    */
    public function showReservation(EntityManagerInterface $entityManager): Response
    {
        $chambres = $entityManager->getRepository(Chambre::class)->findBy(['deletedAt' => null]);
        
        return $this->render('reservation/show_reservation.html.twig', [
            'chambres' => $chambres
        ]);
    } # end function showChambre()

    /**
     * @Route("voir-chambre-reservation{id}", name="show_reservation_chambre", methods={"GET|POST"})
     */
    public function showReservationChambre(Chambre $chambre): Response
    {
        return $this->render("admin/show_chambre_id.html.twig", [
            'chambre' => $chambre
        ]);
    }

    
}
//     /**
//      * @Route("/modifier-chambre_{id}", name="update_chambre", methods={"GET|POST"})
//      */
//     public function updateChambre(Chambre $chambre, Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
//     {
//         $originalPhoto = $chambre->getPhoto();

//         $form = $this->createForm(ChambreFormType::class, $chambre, [
//             'photo' => $originalPhoto
//         ])->handleRequest($request);

//         if($form->isSubmitted() && $form->isValid()) {

//             $chambre->setUpdatedAt(new DateTime());

//             // # L'alias sera utilisé dans l'url (comme FranceTvInfo) et donc doit être assaini de tout accents et espaces.
//             // $chambre->setAlias($slugger->slug($chambre->getTitle()));

//             /** @var UploadedFile $photo */
//             $photo = $form->get('photo')->getData();

//             if($photo) {
//                 $extension = '.' . $photo->guessExtension();
//                 $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);
//                 $safeFilename = $slugger->slug($originalFilename);
// //                $safeFilename = $chambre->getAlias();

//                 $newFilename = $safeFilename . '_' . uniqid() . $extension;

//                 try {
//                     $photo->move($this->getParameter('uploads_dir'), $newFilename);
//                     $chambre->setPhoto($newFilename);
//                 }
//                 catch(FileException $exception) {
//                     # Code à exécuter en cas d'erreur.
//                 }
//             } else {
//                 $chambre->setPhoto($originalPhoto);
//             } # end if($photo)

//             $entityManager->persist($chambre);
//             $entityManager->flush();

//             $this->addFlash('success', "La chambre a bien été modifiée !");
//             return $this->redirectToRoute('show_chambres');
//         } # end if ($form)

//         return $this->render("admin/form/gestion_chambre.html.twig", [
//             'form' => $form->createView(),
//             'chambre' => $chambre
//         ]);
//     }# end function updateChambre

//     /**
//      * @Route("/supprimer-chambre_{id}", name="hard_delete_chambre", methods={"GET"})
//      */
//     public function hardDeleteChambre(Chambre $chambre, EntityManagerInterface $entityManager): RedirectResponse
//     {
//         $photo = $chambre->getPhoto();

//         unlink($this->getParameter('uploads_dir'). '/' . $photo);

//         $entityManager->remove($chambre);
//         $entityManager->flush();

//         $this->addFlash('success', "La chambre a bien été supprimée de la base de données.");
//         return $this->redirectToRoute('show_chambres');
//     } #end admin chambre
// } # end class

templates/reservation/commande_chambre.html.twig
{% extends "base.html.twig" %}

{% block title %}Confirmer réservation{% endblock %}

{% block body %}

<div class="row">
		<div class="col-8 mx-auto">
			{{ form_start(form) }}

                <div class="row">
                    <div class="col-6">{{ form_row(form.firstname) }}</div>
                    <div class="col-6">{{ form_row(form.lastname) }}</div>
                </div>
                <div class="row">
                    <div class="col-6">{{ form_row(form.phone) }}</div>
                    <div class="col-6">{{ form_row(form.email) }}</div>

                </div>

			{{ form_end(form) }}

            {% endblock %}

templates/reservation/reservation_chambre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation de la chambre {id}
{% endblock %}

{% block body %}

	<h1 class="text-center my-4">Réservation de la chambre {id}</h1>

		<div class="row">
			<div class="col-4 mx-auto my-4">
				<p class="text-center">

					{{ chambre.title }}

				</p>
				<p class="text-center">

					{{ chambre.descriptionShort }}

				</p>
				<p class="text-center">

					{{ chambre.descriptionLong }}

				</p>
			</div>
			<div class="col-4 mx-auto my-4">
				<a href"">
					<img src=" {{ asset('uploads/' ~ chambre.photo) }}" width='300' height='200' alt=""></a>
			</div>


	{% endblock %}

templates/reservation/show_reservation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos chambres - HouseHotel
{% endblock %}

{% block body %}

	<h1 class="text-center my-4">Nos chambres</h1>


	{% for chambre in chambres %}


		<div class="row">
			<div class="col-4 mx-auto my-4">
				<p class="text-center">

					{{ chambre.title }}

				</p>
				<p class="text-center">

					{{ chambre.descriptionShort }}

				</p>
				<p class="text-center">

					{{ chambre.descriptionLong }}

				</p>
			</div>
			<div class="col-4 mx-auto my-4">
				<a href"">
					<img src=" {{ asset('uploads/' ~ chambre.photo) }}" width='300' height='200' alt=""></a>
			</div>

		
				<div class="row">
					<div class="col-4 mx-auto my-4">
						<a href="{{ path('commande_chambre', {'id': chambre.id}) }}" class="btn btn-primary">
							<i class="fa-solid fa-plus"></i>
							Réserver une chambre</a>
				
				</div>
			</div>

		{% endfor %}


	{% endblock %}