src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Chambre::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $chambre;

    /**
     * @ORM\Column(type="date")
     */
    private $date_arrival;

    /**
     * @ORM\Column(type="date")
     */
    private $date_departure;

    /**
     * @ORM\Column(type="integer")
     */
    private $price_total;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_register;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChambre(): ?Chambre
    {
        return $this->chambre;
    }

    public function setChambre(?Chambre $chambre): self
    {
        $this->chambre = $chambre;

        return $this;
    }

    public function getDateArrival(): ?\DateTimeInterface
    {
        return $this->date_arrival;
    }

    public function setDateArrival(\DateTimeInterface $date_arrival): self
    {
        $this->date_arrival = $date_arrival;

        return $this;
    }

    public function getDateDeparture(): ?\DateTimeInterface
    {
        return $this->date_departure;
    }

    public function setDateDeparture(\DateTimeInterface $date_departure): self
    {
        $this->date_departure = $date_departure;

        return $this;
    }

    public function getPriceTotal(): ?int
    {
        return $this->price_total;
    }

    public function setPriceTotal(int $price_total): self
    {
        $this->price_total = $price_total;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateRegister(): ?\DateTimeInterface
    {
        return $this->date_register;
    }

    public function setDateRegister(\DateTimeInterface $date_register): self
    {
        $this->date_register = $date_register;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }
    
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Commande;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CommandeController extends AbstractController
{

    /**
    *@Route("/voir-commandes_{id}", name="show_commande", methods={"GET"}))
    */
    public function showCommande(EntityManagerInterface $entityManager): Response
    {
    $commande = $entityManager->getRepository(Commande::class)->findAll();
    return $this->render("/commande/show_commande.html.twig", [
    'commande' => $commande
    ]);
    }

    /**
     * @Route("/ajouter-une-commande_{id}", name="create_commande", methods={"GET|POST"})
     */
    public function createCommande(Request $request, EntityManagerInterface $entityManager): Response
    {
        # 1 - Instanciation
        $commande = new Commande();

        # 2 - Création du formulaire
        $form = $this->createForm(CommandeFormType::class, $commande)
            ->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $commande->setCreatedAt(new DateTime());
            $commande->setUpdatedAt(new DateTime());

            #3 Ajout des data de commande
             $commande->getId();
             $commande->getFirstname();
             $commande->getChambre();
             $commande->getChambre();
             $commande->getDateArrival();
             $commande->getDateDeparture();
             $commande->getFirstname();
             $commande->getLastname();
             $commande->getPhone();
             $commande->getEmail();
             

                $entityManager->persist($commande);
                $entityManager->flush();

                $this->addFlash('success', "Votre commande Administrateur a bien été ajoutée.");
                return $this->redirectToRoute('show_commande');

        } # end if ($form)

        # 4 - Création de la vue
        return $this->render("commande\show_commande.html.twig", [
            'form' => $form->createView(),
    
        ]);
    } # end function createCommande


    /**
     * @Route("/modifier-commande_{id}", name="update_commande", methods = {"GET|POST"})
     */
    public function updateCommande(Commande $commande, Request $request, EntityManagerInterface $entityManager): Response
    {        
             $form = $this->createForm(CommandeFormType::class, $commande)->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid())
    {
      
            $commande->setUpdatedAt(new DateTime());

        $entityManager->persist($commande);
        $entityManager->flush();

       
        $this->addFlash('success', "La commande a été modifiée avec succès !");
        return $this->redirectToRoute('show_commande');
        }
        $commande = $entityManager->getRepository(Commande::class)->findById();

        return $this->render("admin/form/gestion_commandes.html.twig", [
            'form' => $form->createView(),
            'commande' => $commande
        ]); 
    } # end funct


     /**
     * @Route("/archiver-commande_{id}", name="soft_delete_commande", methods={"GET"})
     */
    public function archiverCommande(Commande $commande, EntityManagerInterface $entityManager):  Response
    {     
        $commande->setDeletedAt(new DateTime());
        $commande->setUpdatedAt(new DateTime());

            $entityManager->persist($commande);
            $entityManager->flush();

        $this->addFlash('success', "La commande a bien été archivée");
        return $this->redirectToRoute("show_commande"); 

}

 /**
     * @Route("/restaurer-une-commande_{id}", name="restore_commande", methods={"GET"})
     */
    public function restoreCommande(Commande $commande, EntityManagerInterface $entityManager): Response
    {
        $commande->setDeletedAt(null);

        $entityManager->persist($commande);
        $entityManager->flush();

        $this->addFlash('success', "La commande a bien été restaurée");
        return $this->redirectToRoute('show_commandes');
    }

    /**
     * @Route("/voir-les-commandes-archivees_{id}", name="show_trash", methods={"GET"})
     */
    public function showTrash(EntityManagerInterface $entityManager): Response
    {
        $archivedCommandes = $entityManager->getRepository(Commande::class)->findByTrash();

        return $this->render("admin/trash/commande_trash.html.twig", [
            'archivedCommandes' => $archivedCommandes,
        ]);
    }


}

templates/commande/show_commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des commandes
{% endblock %}

{% block body %}

	<h1 class="text-center my-4">Gestion des commandes</h1>
    <div class="row">
					<div class="col-6 mx-auto my-4">
						<a href="{{ path('create_commande',{"id": commande.id}) ) }}" class="btn btn-primary">
							<i class="fa-solid fa-plus"></i>
							Ajouter une commande</a>
				</div>
			</div>

	<div class="row">
		<div
			class="col-6 mx-auto">
            {% include 'include/_flashes.html.twig' %}
		</div>
	</div>

    <div class="row">
        <div class="col-10 mx-auto my-4">

            <h2 class="text-center"></h2>

            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Chambre</th>
                    <th>Date de checkin</th>
                    <th>Date de checkout</th>
                    <th>Prix total</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Téléphone</th>
                    <th>Email</th>
                    <th>Date et heure d'enregistrement</th>
                    <th>Modifié le</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for commande in commandes %}
                    <tr>
                        <td>{{ commande.id }}</td>
                        <td>{{ commande.chambre }}</td>
                        <td>{{ commande.dateArrival }}</td>
                        <td>{{ commande.dateDeparture }}</td>
                        <td>{{ commande.priceTotal }}</td>
                        <td>{{ commande.firstname}}</td>
                        <td>{{ commande.lastname }}</td>
                        <td>{{ commande.phone}}</td>
                        <td>{{ commande.email}}</td>
                        <td>{{ commande.phone}}</td>
                        <td>{{ commande.createdAt | date('d/m/Y') }}</td>
                        <td>
                            <a href="{{ path('show_commande', {"id": commande.id}) }}" class="text-info" title="Voir la commande"><i class="fa-solid fa-magnifying-glass"></i></a>
                            <a href="{{ path('update_commande', {"id": commande.id}) }}" class="text-info" title="Modifier la commande"><i class="fa-solid fa-pen-to-square"></i></a>
                            <a href="{{ path('soft_delete_commande', {'id': commande.id}) }}" class="text-info" title="Archiver l'article" onclick="return confirm('Voulez-vous archiver cette commande ?')"><i class="fa-solid fa-folder-arrow-down"></i>/a>
                            <a href="{{ path('restore_commande', {'id': commande.id}) }}" class="text-info" title="Archiver la commande" onclick="return confirm('Voulez-vous restorer cette commande ?')"><i class="fa-solid fa-trash-arrow-up"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}